---
- name: install dockerize-unpack script
  get_url:
    dest=/usr/local/bin/dockerize-unpack
    force=yes
    url="https://raw.github.com/modcloth-labs/dockerize/{{ dockerize_unpack.script_rev }}/bin/dockerize-unpack"
    mode=0755
  tags:
    - dockerize
    - dockerize-unpack

- name: pull docker container
  action: shell docker pull "{{ item.image_name }}:{{ item.image_tag }}"
  with_items: dockerize_unpack_list

- name: run dockerize-unpack script
  shell: /usr/local/bin/dockerize-unpack "{{ item.image_name }}:{{ item.image_tag }}" "{{ item.script_addl_args }}"
  with_items: dockerize_unpack_list
